const ugCourses = {
    "Arts": {
        "BBA": "Bachelor of Business Administration",
        "BMS": "Bachelor of Management Science",
        "BFA": "Bachelor of Fine Arts",
        "BEM": "Bachelor of Event Management",
        "BA + LL.B": "Integrated Law Course",
        "BJMC": "Bachelor of Journalism and Mass Communication",
        "BFD": "Bachelor of Fashion Designing",
        "BSW": "Bachelor of Social Work",
        "BBS": "Bachelor of Business Studies",
        "BTTM": "Bachelor of Travel and Tourism Management",
        "Aviation Courses": "Aviation Courses",
        "B.Sc.- Interior Design": "B.Sc.- Interior Design",
        "B.Sc.- Hospitality and Hotel Administration": "B.Sc.- Hospitality and Hotel Administration",
        "B.Design": "Bachelor of Design (B. Design)",
        "Bachelor of Performing Arts": "Bachelor of Performing Arts",
        "BA in History": "BA in History"
    },
    "Science": {
        "BE/B.Tech": "Bachelor of Technology",
        "B.Arch": "Bachelor of Architecture",
        "BCA": "Bachelor of Computer Applications",
        "B.Sc.- Information Technology": "B.Sc.- Information Technology",
        "B.Sc.- Nursing": "B.Sc.- Nursing",
        "BPharma": "Bachelor of Pharmacy",
        "B.Sc.- Interior Design": "B.Sc.- Interior Design",
        "BDS": "Bachelor of Dental Surgery",
        "Animation, Graphics and Multimedia": "Animation, Graphics and Multimedia",
        "B.Sc. – Nutrition & Dietetics": "B.Sc. – Nutrition & Dietetics",
        "BPT- Bachelor of Physiotherapy": "BPT- Bachelor of Physiotherapy",
        "B.Sc.- Applied Geology": "B.Sc.- Applied Geology",
        "BA/B.Sc. Liberal Arts": "BA/B.Sc. Liberal Arts",
        "B.Sc.- Physics": "B.Sc.- Physics",
        "B.Sc. Chemistry": "B.Sc. Chemistry",
        "B.Sc. Mathematics": "B.Sc. Mathematics",
        "B.Sc. Computer Science": "B.Sc. Computer Science",
        "Engineering": {
            "Aeronautical Engineering": "Aeronautical Engineering",
            "Automobile Engineering": "Automobile Engineering",
            "Civil Engineering": "Civil Engineering",
            "Computer Science and Engineering": "Computer Science and Engineering",
            "Biotechnology Engineering": "Biotechnology Engineering",
            "Electrical and Electronics Engineering": "Electrical and Electronics Engineering",
            "Electronics and Communication Engineering": "Electronics and Communication Engineering",
            "Automation and Robotics": "Automation and Robotics",
            "Petroleum Engineering": "Petroleum Engineering",
            "Instrumentation Engineering": "Instrumentation Engineering",
            "Ceramic Engineering": "Ceramic Engineering",
            "Chemical Engineering": "Chemical Engineering",
            "Structural Engineering": "Structural Engineering",
            "Transportation Engineering": "Transportation Engineering",
            "Construction Engineering": "Construction Engineering",
            "Power Engineering": "Power Engineering",
            "Robotics Engineering": "Robotics Engineering",
            "Textile Engineering": "Textile Engineering",
            "Smart Manufacturing & Automation": "Smart Manufacturing & Automation"
        }
    },
    "Commerce": {
        "B.Com": "Bachelor of Commerce",
        "BBA": "Bachelor of Business Administration",
        "B.Com (Hons.)": "B.Com (Hons.)",
        "Integrated Law Program- B.Com LL.B.": "Integrated Law Program- B.Com LL.B.",
        "Integrated": "Integrated Law Program- BBA LL.B",
        "Chartered Accountancy": "Chartered Accountancy",
        "Company Secretary": "Company Secretary",
        "Bachelor of Design": "Bachelor of Design",
        "Bachelor in Foreign Language": "Bachelor in Foreign Language",
        "Diploma Courses": "Diploma Courses",
        "Advanced Diploma Courses": "Advanced Diploma Courses",
        "Certificate Courses": "Certificate Courses",
    }
}