 const advancedPrograms = {
    "Advanced Program": "Advanced Program",
    "Executive Fellow Program In Management (E.F.P.M)": "E.F.P.M",
    "Executive Management Programme (E.M.P)": "E.M.P",
    "Executive Post Graduate Certificate (Executive PG Certificate)": "Executive PG Certificate",
    "Executive Post Graduate Programme (Executive PG Programme)": "Executive PG Programme",
    "Fellow Programme (Fellow Programme)": "Fellow Programme",
    "International Programme (International Programme)": "International Programme",
    "Master of Law (LL.M)": "LL.M",
    "Master of Arts (M.A)": "M.A",
    "Master of Arts in Management (M.A.M)": "M.A.M",
    "Master of Arts in Personal Management (M.A.P.M)": "M.A.P.M",
    "Master of Architecture (M.Arch)": "M.Arch",
    "Master of Business Administration (M.B.A)": "M.B.A",
    "Master of Business Economics (M.B.E)": "M.B.E",
    "Master of Business Laws (M.B.L)": "M.B.L",
    "Master of Business Management (M.B.M)": "M.B.M",
    "Master of Business Studies (M.B.S)": "M.B.S",
    "Master of Computer Applications (M.C.A)": "M.C.A",
    "Master Of Communication And Journalism (M.C.J)": "M.C.J",
    "Master of Comparative Laws (M.C.L)": "M.C.L",
    "Master of Computer Management (M.C.M)": "M.C.M",
    "Master of Corporate Secretaryship (M.C.S)": "M.C.S",
    "Master of Chirurgical (M.Ch)": "M.Ch",
    "Master of Commerce (M.Com)": "M.Com",
    "Doctor of Medicine (M.D)": "M.D",
    "Management Development Programme (M.D.P)": "M.D.P",
    "Master of Dental Surgery (M.D.S)": "M.D.S",
    "Masters in Design (M.Des)": "M.Des",
    "Master of Engineering (M.E)": "M.E",
    "Master of Education (M.Ed)": "M.Ed",
    "Master of education in Artificial Intelligence (M.Ed AI)": "M.Ed AI",
    "Master of Fine Arts (M.F.A)": "M.F.A",
    "Master of Finance And Control (M.F.C)": "M.F.C",
    "Master of Film Management (M.F.M)": "M.F.M",
    "Master of Financial Services (M.F.S)": "M.F.S",
    "Master of Fishery Sciences (M.F.Sc)": "M.F.Sc",
    "Master of Foreign Trade (M.F.T)": "M.F.T",
    "Master of Hospital Administration (M.H.A)": "M.H.A",
    "Master of Hospitality And Hotel Management (M.H.H.M)": "M.H.H.M",
    "Master of Hospitality Management (M.H.M)": "M.H.M",
    "Master of Human Resource Management (M.H.R.M)": "M.H.R.M",
    "Master Of Health Science (M.H.Sc)": "M.H.Sc",
    "Masters of Hospitality and Tourism Management (M.H.T.M)": "M.H.T.M",
    "Master of International Business (M.I.B)": "M.I.B",
    "Masters in International Management (M.I.M)": "M.I.M",
    "Master of Journalism (M.J)": "M.J",
    "Master of Laws (M.L)": "M.L",
    "Master of Library and Information Science (M.L.I.Sc)": "M.L.I.Sc",
    "Master of Labour Management (M.L.M)": "M.L.M",
    "Master of Library Science (M.L.Sc)": "M.L.Sc",
    "Master of Marketing Management (M.M.M)": "M.M.M",
    "Master of Management Program (M.M.P)": "M.M.P",
    "Master of Management Studies (M.M.S)": "M.M.S",
    "Master of Occupational Therapy (M.O.T)": "M.O.T",
    "Master of Performing Arts (M.P.A)": "M.P.A",
    "Master of Psychiatric Epidemiology (M.P.E)": "M.P.E",
    "Master Of Physical Education (M.P.Ed)": "M.P.Ed",
    "Master of Public Health (M.P.H)": "M.P.H",
    "Masters Programme in International Business (M.P.I.B)": "M.P.I.B",
    "Master of Performance Management (M.P.M)": "M.P.M",
    "Masters in Public Systems Management (M.P.S.M)": "M.P.S.M",
    "Master of Physiotherapy (M.P.T)": "M.P.T",
    "Master of Pharmacy (M.Pharma)": "M. Pharma",
    "Master of Philosophy (M.Phil)": "M. Phil",
    "Master of Science (M.S)": "M.S",
    "Master of Social Dynamics (M.S.D)": "M.S.D",
    "Master of Social Work (M.S.W)": "M.S.W",
    "Master of Science (M.Sc)": "M.Sc",
    "Master of Tourism Administrations (M.T.A)": "M.T.A",
    "Master of Tourism Management (M.T.M)": "M.T.M",
    "Master of Technology (M.Tech)": "M.Tech",
    "Master of Theology (M.Th)": "M.Th",
    "Master of Visual Arts (M.V.A)": "M.V.A",
    "Master of Veterinary Science (M.V.Sc)": "M.V.Sc",
    "Master of Vocational (M.Voc)": "M.Voc",
    "Master of Business Administration (MBA)": "MBA",
    "Master of Industrial Relation and Personal Management (MIR and PM)": "MIR and PM",
    "Master of Personnel Management (MPM)": "MPM",
    "Master of Personal Management and Industrial Relation (MPM and IR)": "MPM and IR",
    "Post Graduate Programme (PG Programme)": "PG Programme",
    "Doctor of Philosophy (Ph.D)": "Ph."
  };
  